---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.machinePlacement.class.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    garden.sapcloud.io/purpose: machineclass
type: Opaque
data:
  userData: {{ .Values.machinePlacement.class.secret.cloudConfig | b64enc }}
  providerAccessKeyId: {{ .Values.machinePlacement.class.secret.accessKeyID | b64enc }}
  providerSecretAccessKey: {{ .Values.machinePlacement.class.secret.secretAccessKey | b64enc }}
{{- end }}
